### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ohdb** [acidvegas/irc#1]
`[root@x]# python3.3 irc.py
  File "irc.py", line 63
    print(f'{get_time()} | [~] - {msg}')
                                      ^
SyntaxError: invalid syntax
[root@x]# python irc.py
  File "irc.py", line 63
    print(f'{get_time()} | [~] - {msg}')
                                      ^
SyntaxError: invalid syntax`
please help

**Comment by acidvegas** [comment]
As stated in the README file:
"This script was developed to be used with the latest version of Python."

I would imagine you are on debian and do not have the latest Python version which introduced FSTRINGS.

**Comment by ohdb** [comment]
I use centos 7 64x and python3.5?

**Comment by acidvegas** [comment]
Thats cool. Did your Centos build come with a web browser so you can go on Google?

https://www.python.org/downloads/release/python-364/

> "This script was developed to be used with the latest version of Python."
> I use centos 7 64x and python3.5?

I am not sure why this is so confusing to you...
